{application,conduit_amqp,
             [{applications,[kernel,stdlib,elixir,logger,connection,poolboy,
                             conduit,amqp]},
              {description,"AMQP adapter for Conduit."},
              {modules,['Elixir.ConduitAMQP','Elixir.ConduitAMQP.Conn',
                        'Elixir.ConduitAMQP.ConnPool',
                        'Elixir.ConduitAMQP.Meta','Elixir.ConduitAMQP.Props',
                        'Elixir.ConduitAMQP.Pub','Elixir.ConduitAMQP.PubPool',
                        'Elixir.ConduitAMQP.Setup',
                        'Elixir.ConduitAMQP.Setup.State',
                        'Elixir.ConduitAMQP.Sub','Elixir.ConduitAMQP.SubPool',
                        'Elixir.ConduitAMQP.Task','Elixir.ConduitAMQP.Tasks',
                        'Elixir.ConduitAMQP.Topology',
                        'Elixir.ConduitAMQP.Util']},
              {registered,[]},
              {vsn,"0.6.4"}]}.
